// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shelf.Api.Data;

#nullable disable

namespace Shelf.Api.Data.Migrations
{
    [DbContext(typeof(ShelfDb))]
    [Migration("20261009212549_Audio")]
    partial class Audio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("BookTag", b =>
                {
                    b.Property<int>("BooksId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BooksId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("BookTags", (string)null);
                });

            modelBuilder.Entity("Shelf.Api.Books.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("AcquiredOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Acquisition")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioFileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioStoredName")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioTrack")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentPage")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("DueOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EbookChapter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EbookFileName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EbookStoredName")
                        .HasMaxLength(48)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FinishedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Inscription")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("LoanedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoanedTo")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Loved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Queued")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecommendedBy")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Review")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Series")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeriesNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("StartedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subtitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Translator")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Author");

                    b.HasIndex("Status");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Shelf.Api.Books.Highlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChapterIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("NotedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Suffix")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Highlights");
                });

            modelBuilder.Entity("Shelf.Api.Books.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("NotedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Page")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("Shelf.Api.Books.ReadingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FromPage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ToPage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Shelf.Api.Books.ShelfSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearlyGoal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Shelf.Api.Books.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.HasOne("Shelf.Api.Books.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shelf.Api.Books.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shelf.Api.Books.Highlight", b =>
                {
                    b.HasOne("Shelf.Api.Books.Book", "Book")
                        .WithMany("Highlights")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Shelf.Api.Books.Quote", b =>
                {
                    b.HasOne("Shelf.Api.Books.Book", "Book")
                        .WithMany("Quotes")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Shelf.Api.Books.ReadingSession", b =>
                {
                    b.HasOne("Shelf.Api.Books.Book", "Book")
                        .WithMany("Sessions")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Shelf.Api.Books.Book", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("Quotes");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
