@Shelf.Api_HostAddress = http://localhost:5041

GET {{Shelf.Api_HostAddress}}/books
Accept: application/json

###

GET {{Shelf.Api_HostAddress}}/books?q=le%20guin&status=Want&sort=year
Accept: application/json

###

GET {{Shelf.Api_HostAddress}}/books/stats
Accept: application/json

###

POST {{Shelf.Api_HostAddress}}/books
Content-Type: application/json

{
  "title": "A Wizard of Earthsea",
  "author": "Ursula K. Le Guin",
  "status": "Want",
  "year": 1968,
  "pages": 205,
  "isbn": "0-306-40615-2",
  "tags": ["science fiction", "novel"]
}

###

PUT {{Shelf.Api_HostAddress}}/books/1
Content-Type: application/json

{
  "title": "The Left Hand of Darkness",
  "author": "Ursula K. Le Guin",
  "status": "Finished",
  "rating": 5,
  "year": 1969,
  "pages": 304,
  "tags": ["science fiction"]
}

###

POST {{Shelf.Api_HostAddress}}/books/1/quotes
Content-Type: application/json

{
  "text": "The king was pregnant.",
  "page": 1
}

###

DELETE {{Shelf.Api_HostAddress}}/books/1/quotes/1

###

DELETE {{Shelf.Api_HostAddress}}/books/1

###

GET {{Shelf.Api_HostAddress}}/books/lookup?isbn=9780441478125
Accept: application/json

###

POST {{Shelf.Api_HostAddress}}/books/1/return
